# Generated by Django 3.1.2 on 2020-11-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20201107_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='other_information',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='more_info',
        ),
        migrations.AddField(
            model_name='career',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Reference link'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='reference link'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
